# Saturn: https://github.com/kkga/saturn.kak

[colors]
foreground = "#BCBCBC"
background = "#121212"
cursor_bg = "#5FAFAF"
cursor_border = "#5FAFAF"
cursor_fg = "#121212"
selection_bg = "#87AFD7"
selection_fg = "#1C1C1C"

ansi = [
  "#121212",
  "#AF5F5F",
  "#5F875F",
  "#AF875F",
  "#5F87AF",
  "#5F5F87",
  "#5F8787",
  "#8A8A8A",
]

brights = [
  "#6C6C6C",
  "#D7875F",
  "#87AF87",
  "#D7AF5F",
  "#87AFD7",
  "#8787AF",
  "#5FAFAF",
  "#FFFFFF",
]
