#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config window_gap 2

yabai -m config layout float
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config window_placement second_child
yabai -m config split_ratio 0.66
yabai -m config auto_balance off
yabai -m config mouse_modifier ctrl
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

yabai -m rule --add app="Spotify" display=last
yabai -m rule --add app="1Password" manage=off
yabai -m rule --add app="Telegram" manage=off
yabai -m rule --add app="Reminders" manage=off
yabai -m rule --add app="Things" manage=off
yabai -m rule --add app="Latest" manage=off
yabai -m rule --add app="Pandan" manage=off
yabai -m rule --add app="CleanShot" manage=off
yabai -m rule --add app="System Settings" manage=off
yabai -m rule --add app="IINA" manage=off
yabai -m rule --add app="App Store" manage=off
yabai -m rule --add app="Activity Monitor" manage=off
yabai -m rule --add app="Preview" manage=off
yabai -m rule --add app="Kap" manage=off
yabai -m rule --add app="Bitwarden" manage=off
yabai -m rule --add app="iStat Menus Status" manage=off
yabai -m rule --add app="Quick Add to Trello" manage=off
yabai -m rule --add app="zoom.us" manage=off
yabai -m rule --add app="Transmission" manage=off
yabai -m rule --add app="espanso" manage=off
yabai -m rule --add app="Godot" manage=off
yabai -m rule --add app="Stats" manage=off
yabai -m rule --add app="Dark Noise" manage=off
yabai -m rule --add app="Fantastical" manage=off
yabai -m rule --add app="Mullvad VPN" manage=off
yabai -m rule --add app="Mullvad VPN" sticky=on
yabai -m rule --add app="Velja" manage=off
yabai -m rule --add app="Simulator" manage=off
yabai -m rule --add app="AmneziaVPN" manage=off
yabai -m rule --add app="Airflow" manage=off
yabai -m rule --add title="popup" manage=off

# suggested fix for yabai 6.0 layer change
# https://github.com/koekeishiya/yabai/issues/1912
# yabai -m rule --add app=".*" layer=normal
# yabai -m signal --add event=application_front_switched action="yabai -m window --layer normal"
