matches:
  - trigger: "@@"
    replace: "me@kkga.me"

  - trigger: "@!"
    replace: "gadzhi.kha@gmail.com"

  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y/%m/%d"

  - trigger: ":ddate"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%YYYY/%mm/%d"


  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

