#!/bin/sh

response="$(curl -s https://am.i.mullvad.net/json)"
echo $response
connected="$(echo "$response" | jq '.mullvad_exit_ip')"

if [ "$connected" = "true" ]; then
	hostname="$(echo "$response" | jq -r '.mullvad_exit_ip_hostname' | sed 's/-wireguard//')"
	echo "connected|bool|true"
	echo "hostname|string|$hostname"
	echo ""
else
	echo "connected|bool|false"
	echo ""
fi
