#!/bin/sh

cd "$HOME" || return

STATUS=$(git --git-dir "$DOT_GITDIR" status --porcelain --short |
	sed 's/$/\\n/' |
	sed 's/^ M /<b>M:<\/b> /' |
	sed 's/^ A /<b>A:<\/b> /' |
	tr -d '\n')
COUNT=$(printf "%b" "$STATUS" | wc -l)

echo "count|int|$COUNT"
echo ""
