#!/bin/sh

cd "$HOME" || return

STATUS=$(git --git-dir "$DOT_GITDIR" status --porcelain --short |
	sed 's/$/\\n/' |
	sed 's/^ M /<b>M:<\/b> /' |
	sed 's/^ A /<b>A:<\/b> /' |
	tr -d '\n')
COUNT=$(printf "%b" "$STATUS" | wc -l)

if [ "$COUNT" -gt 0 ]; then
	printf '{"text": "%s", "tooltip": "%s"}\n' "$COUNT" "$STATUS"
else
	printf ''
fi
