#!/bin/sh

render() {
	response="$(curl -s https://am.i.mullvad.net/json)"
	connected="$(echo "$response" | jq '.mullvad_exit_ip')"

	if [ "$connected" = "true" ]; then
		country="$(echo "$response" | jq -r '.country')"
		hostname="$(echo "$response" | jq -r '.mullvad_exit_ip_hostname')"
		class="connected"
		printf '{"text": "%s", "tooltip": "%s", "class": "%s"}\n' "vpn" "$country - $hostname" "$class"
	else
		printf '{"text": ""}\n'
	fi
}

render
