#!/bin/sh
#
# Shows the calendar event that's happening now, of the next on if there isn't
# one.
# https://git.sr.ht/~whynothugo/dotfiles/tree/main/item/home/.local/lib/waybar-khal

render() {
	# Find events starting in two minutes.
	# So if my current event ends in two minutes and another one starts, the
	# widget is already updated with what's upcoming.
	SINCE="$(date -d 'now +2 min' '+%d-%m-%Y %H:%M')"
	UNTIL="$(date -d 'now +1 day' '+%d-%m-%Y %H:%M')"

	DATE="$(date -d 'now' '+%a %d %b')"

	# TODO: On overlap, try to prefer the event where I've confirmed attendance.

	EVENTS="$(
		khal --no-color list "$SINCE" "$UNTIL" \
			--day-format "<span weight=\"bold\"># {name}</span>" \
			--format "{start-end-time-style} {title:.40}{repeat-symbol}" |
			grep -v -P '↦|↔ |⇥' | # filter out continuing all day events
			grep -v '\[Lunch\]' | # filter out lunch
			grep -v 'No events' | # filter when no events
			grep -v '^ '          # exclude full-day events
	)"

	# get todoman tasks due in the next 24 hours
	TODOS="$(todo --porcelain list --due 24 | jq -r 'map("- "+.summary+" "+"("+(.due | strflocaltime("%b %d"))+")") | join("\n")')"

	TEXT="$DATE"
	TOOLTIP=""

	if [ -z "$EVENTS" ] && [ -z "$TODOS" ]; then
		CLASS="no-event"
	else
		CLASS="event"
		[ "$EVENTS" ] && TOOLTIP="$(printf "%b\n\n" "$EVENTS")"
		[ "$EVENTS" ] && [ "$TODOS" ] && TOOLTIP="$(printf "%b\n\n" "$TOOLTIP" "<span weight=\"bold\"># Todos</span>")"
		[ "$TODOS" ] && TOOLTIP="$(printf "%b\n" "$TOOLTIP" "$TODOS")"
	fi

	jq --compact-output \
		--raw-output \
		--null-input \
		--arg text "$TEXT" \
		--arg class "$CLASS" \
		--arg tooltip "$TOOLTIP" \
		'{"text": $text, "class": $class, "tooltip": $tooltip}'
}

render
