#!/bin/sh

failed_user="$(systemctl --plain --no-legend --user list-units --state=failed | awk '{ print $1 }')"
failed_system="$(systemctl --plain --no-legend list-units --state=failed | awk '{ print $1 }')"

failed_systemd_count="$(echo -n "$failed_system" | grep -c '^')"
failed_user_count="$(echo -n "$failed_user" | grep -c '^')"

total_failed=$((failed_systemd_count + failed_user_count))

if [ "$total_failed" -eq 0 ]; then
	echo "failed|bool|false"
	echo ""
else
	echo "failed|bool|true"
	echo "failed_system|int|$failed_systemd_count"
	echo "failed_user|int|$failed_user_count"
	echo ""
fi
